version: '3.0'

services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M